# Generated by Django 4.1.7 on 2023-03-27 20:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_cars_options_alter_cars_doors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
    ]
